fluent-bit:
  fullnameOverride: "fluent-bit-http"

  image:
    repository: coralogixrepo/coralogix-fluent-bit-multiarch
    tag: v0.0.2

  serviceMonitor:
    enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 250Mi



  # The private key must exist under the field 'PRIVATE_KEY' in a secret called 'integrations-privatekey' in the same namsespace as the daemonset
  envFrom:
    - secretRef:
        name: integrations-privatekey

  #prometheusRule:
  #  enabled: true
  #  rules:
  #  - alert: FluentbitNoOutputBytesProcessed
  #    expr: rate(fluentbit_output_proc_bytes_total[5m]) == 0
  #    annotations:
  #      description: |
  #        "FluentBit instance {{$labels.instance}}'s output plugin {{$labels.name}} has not processed any
  #        bytes for at least 15 minutes."
  #      summary: No Output Bytes Processed
  #    for: 2m
  #    labels:
  #      severity: critical
  #  - alert: FluentbitErrorRateIncreased
  #    expr: sum(rate(fluentbit_output_retries_failed_total[5m])) > 0
  #    annotations:
  #      description: |
  #        "FluentBit experiencing connectivity issues with Coralogix, issue may cause missing data for Coralogix"
  #      summary: Retries failed
  #    for: 2m
  #    labels:
  #      severity: critical
  #  - alert: FluentbitNoInput
  #    expr: sum by (pod) (rate(fluentbit_input_bytes_total[5m])) == 0 
  #    annotations:
  #      description: |
  #        "FluentBit is having 0 data incoming, restart the pod  {{$labels.pod}}"
  #      summary: FluentBit no input coming 
  #    for: 2m
  #    labels:
  #      severity: warning

  rbac:
    nodeAccess: true

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  env:
  - name: APP_NAME_SYSTEMD
    value: systemd 
  - name: SUB_SYSTEM_SYSTEMD
    value: _SYSTEMD_UNIT
  - name: HOSTNAME
    valueFrom:
      fieldRef:  
        apiVersion: v1
        fieldPath: metadata.name

  # The same usage as env, but used for passing dynamic values to the chart using the helm argument "--set <variable>=<value>"
  envWithTpl:
  - name: APP_NAME
    value: "{{ .Values.app_name }}"
  - name: SUB_SYSTEM
    value: "{{ .Values.sub_system }}"
  - name: ENDPOINT
    value: "{{ .Values.endpoint }}"

  endpoint: api.eu2.coralogix.com
  app_name: kubernetes.namespace_name
  sub_system: kubernetes.container_name
  logLevel: error

  config: 
    service: |-
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level {{.Values.logLevel}}
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{.Values.service.port}}
          Health_Check On
          storage.metrics on

    inputs: |-
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Refresh_Interval 5
          Skip_Long_Lines On
          Mem_Buf_Limit 25MB
          DB /var/log/fluentbit-tail.db

      @INCLUDE input-systemd.conf

    filters: |-
      [FILTER]
          Name kubernetes
          Match kube.*
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
          Use_Kubelet On
          Annotations Off
          Labels On
          Buffer_Size 0
          Keep_Log Off
          Merge_Log_Key log_obj
          Merge_Log On

      [FILTER]
          Name            nest
          Match           kube.*
          Operation       lift
          Nested_under    kubernetes
          Add_prefix      kubernetes.

      [FILTER]
          Name    modify
          Match   kube.*
          Copy    ${APP_NAME} applicationName
          Copy    ${SUB_SYSTEM} subsystemName 

      [FILTER]
          Name            nest
          Match           kube.*
          Operation       nest
          Wildcard        kubernetes.*
          Nest_under      kubernetes
          Remove_prefix   kubernetes.

      [FILTER]
          Name        nest
          Match       kube.*
          Operation   nest
          Wildcard    kubernetes
          Wildcard    log
          Wildcard    log_obj
          Wildcard    stream
          Wildcard    time 
          Nest_under  json 

      @INCLUDE filters-systemd.conf

    outputs: |-
      [OUTPUT]
          Name                  http
          Match                 kube.*
          Host                  ${ENDPOINT}
          Port                  443
          URI                   /logs/rest/singles
          Format                json_lines
          TLS                   On
          Header                private_key ${PRIVATE_KEY}
          compress              gzip
          Retry_Limit           False

      @INCLUDE output-systemd.conf
    
    extraFiles:
      input-systemd.conf: |-    
        [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On 
          Mem_Buf_Limit 5MB  

      filters-systemd.conf: |-
        [FILTER]
          Name    modify
          Match   host.*
          Add    applicationName ${APP_NAME_SYSTEMD} 
          Add    subsystemName ${SUB_SYSTEM_SYSTEMD} 

        [FILTER]
          Name        nest
          Match       host.*
          Operation   nest
          Wildcard    _HOSTNAME
          Wildcard    SYSLOG_IDENTIFIER
          Wildcard    _CMDLINE 
          Wildcard    MESSAGE
          Nest_under  json 

      output-systemd.conf: |-
        [OUTPUT]
          Name                  http
          Match                 host.*
          Host                  ${ENDPOINT}
          Port                  443
          URI                   /logs/rest/singles
          Format                json_lines
          TLS                   On
          Header                private_key ${PRIVATE_KEY}
          compress              gzip
          Retry_Limit           10
