global:
  domain: "coralogix.com"
  defaultApplicationName: "default"
  defaultSubsystemName: "nodes"
  fullnameOverride: otel-coralogix
  # Old endpoint based configuration,
  # please use domain instead.
  traces:
    endpoint: ""
  metrics:
    endpoint: ""
  logs:
    endpoint: ""
