fluentd: 
  fullnameOverride: "fluentd-coralogix"

  image:
    repository: coralogixrepo/coralogix-fluentd-multiarch
    tag: v0.0.1

  resources:
    requests:
      cpu: 800m
      memory: 900Mi
    limits:
      cpu: 800m
      memory: 900Mi

  configMapConfigs:
    - fluentd-prometheus-conf
    - fluentd-systemd-conf

  tolerations:
    - operator: Exists

  dashboards:
    enabled: false

  env:
  - name: APP_NAME
    value: $kubernetes.namespace_name
  - name: SUB_SYSTEM
    value: $kubernetes.container_name
  - name: APP_NAME_SYSTEMD
    value: systemd
  - name: SUB_SYSTEM_SYSTEMD
    value: kubelet.service
  - name: ENDPOINT 
    value: api.eu2.coralogix.com
  - name: "FLUENTD_CONF"
    value: "../../etc/fluent/fluent.conf"
  - name: LOG_LEVEL
    value: error
  - name: MAX_LOG_BUFFER_SIZE
    value: "12582912"
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName

  envFrom:
    - secretRef:
        name: integrations-privatekey

  metrics:
    serviceMonitor:
      enabled: true
  #  prometheusRule:
  #    enabled: true
  #    rules:
  #    - alert: FluentdErrors
  #      expr: sum(rate(fluentd_output_status_num_errors{}[5m])) by (plugin_id) > 0 
  #      for: 1m
  #      labels:
  #        severity: critical
  #      annotations:
  #        summary: "Fluentd Failed to send data to Coralogix"
  #        description: "Fluentd is failing to send data to Coralogix"
  #    - alert: FluentdRetriesHigh
  #      expr: sum(rate(fluentd_output_status_retry_count{}[5m])) by (plugin_id) > 0
  #      for: 4m
  #      labels:
  #        severity: warning
  #      annotations:
  #        summary: "Fluentd is performing many retries to Coralogix"
  #        description: "Fluentd have retries to Coralogix"
  #    - alert: FluentdNoOutPut
  #      expr: sum(rate(fluentd_output_status_emit_records{}[5m])) == 0
  #      for: 4m
  #      labels:
  #        severity: warning
  #      annotations:
  #        summary: "Fluentd is not sending data to Coralogix"
  #        description: "No data on Coralogix"
  #    - alert: FluentdNoInput
  #      expr: sum by (pod) (rate(fluentd_input_status_num_records_total{}[5m])) == 0
  #      for: 2m
  #      labels:
  #        severity: warning
  #      annotations:
  #        summary: "Fluentd is not getting any data"
  #        description: "No data on Coralogix"

  fileConfigs:
    coralogix.conf: |-
      <system>
        log_level "#{ENV['LOG_LEVEL']}"
      </system>
      
      <source>
        @type tail
        @id in_tail_container_logs
        path /var/log/containers/*.log
        pos_file /var/log/fluentd-containers.log.pos
        tag kubernetes.*
        read_from_head false
        <parse>
          @type cri
        </parse>
      </source>
      
      <filter kubernetes.**>
        @type kubernetes_metadata
        @id filter_kube_metadata
        skip_labels false
        skip_container_metadata false
        skip_namespace_metadata true
        skip_master_url true
      </filter>
      
      <filter kubernetes.**>
        @type record_transformer
        remove_keys "$['message']"
        <record>
          log_obj ${record["message"]}
        </record>
      </filter>
      
      <match **>
        @type relabel
        @label @DISPATCH
      </match>
      
      <label @DISPATCH>
        <filter **>
          @type prometheus
          <metric>
            name fluentd_input_status_num_records_total
            type counter
            desc The total number of incoming records
          </metric>
        </filter>
        
        <match internal-kubernetes.systemd>
          @type           coralogix
          endpoint        "#{ENV['ENDPOINT']}"
          privatekey      "#{ENV['PRIVATE_KEY']}"
          appname         "#{ENV['APP_NAME_SYSTEMD']}"
          subsystemname   "#{ENV['SUB_SYSTEM_SYSTEMD']}"
          is_json         true
        </match>
        
        <match kubernetes.**>
          @type           coralogix
          endpoint        "#{ENV['ENDPOINT']}"
          privatekey      "#{ENV['PRIVATE_KEY']}"
          appname         "#{ENV['APP_NAME']}"
          subsystemname   "#{ENV['SUB_SYSTEM']}"
          is_json         true
        </match>
      </label>
    
    02_filters.conf: |-
    01_sources.conf: |-
    03_dispatch.conf: |-
    04_outputs.conf: |-
