apiVersion: v2
name: prometheus-agent-coralogix
description: Prometheus running in agent mode
version: 0.0.16
appVersion: v2.42.0
keywords:
  - prometheus
  - agent
maintainers:
  - name: support
    email: support@coralogix.com
