receivers:
  docker_stats:
    endpoint: 'unix:///var/run/docker.sock'
  hostmetrics:
    collection_interval: 60s
    root_path: /hostfs
    scrapers:
      load:
      filesystem:
      memory:
      network:
      paging:
      cpu:
      disk:
      process:
        exclude:
          names: [ otelcol-contrib ]
          match_type: strict
        mute_process_name_error: true
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 60s
          static_configs:
            - targets: ['0.0.0.0:8888']
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
  batch/metrics:
    timeout: 60s
  resourcedetection/ecs:
    detectors: [env, ecs]
    timeout: 2s
    override: false
exporters:
  logging:
  coralogix:
    traces:
      endpoint: "$TRACES_ENDPOINT"
    private_key: "$PRIVATE_KEY"
    application_name: "OTel"
    subsystem_name: "ECS"
    application_name_attributes:
    - "APP_NAME"
    - "service.namespace"
    subsystem_name_attributes:
    - "SUB_SYS"
    - "aws.ecs.task.family"
    - "service.name"
    timeout: 30s
service:
  pipelines:
    traces:
      exporters:
        - coralogix
        - logging
      processors:
        - batch
        - resourcedetection/ecs
      receivers:
        - otlp
    metrics:
      exporters:
        - coralogix
        - logging
      processors:
        - batch
        - resourcedetection/ecs
      receivers:
        - hostmetrics
        - prometheus
        - docker_stats