name: chart-bump-checks
on:
  pull_request:
    paths:
      - '!**.md' # ignore changes to markdown files

jobs:
  check-chart-version:
    runs-on: ubuntu-latest
    name: Check Helm chart version bump
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: | # Determine where the chart change occured and run the appropriate check.
          logs-fluent-bit-coralogix:
            - 'logs/fluent-bit/k8s-helm/coralogix/**'
          logs-fluent-bit-http:
            - 'logs/fluent-bit/k8s-helm/http/**'
          logs-fluentd-coralogix:
            - 'logs/fluentd/k8s-helm/coralogix/**'
          logs-fluentd-http:
            - 'logs/fluentd/k8s-helm/http/**'
          otel-agent:
            - 'otel-agent/k8s-helm/**'
          otel-infrastructure-collector:
            - 'otel-infrastructure-collector/k8s-helm/**'
          otel-integration:
            - 'otel-integration/k8s-helm/**'
          metrics-prometheus-agent:
            - 'metrics/prometheus-agent/**'
          metrics-prometheus-operator:
            - 'metrics/prometheus/operator/**'
      # Look for `+version` string in the diff to detect if chart has been bumped.
    - name: Fluent-Bit-Coralogix Chart
      if: steps.filter.outputs.logs-fluent-bit-coralogix == 'true'
      run: scripts/version_bump_check.sh logs/fluent-bit/k8s-helm/coralogix
    - name: Fluent-Bit-HTTP Chart
      if: steps.filter.outputs.logs-fluent-bit-http == 'true'
      run: scripts/version_bump_check.sh logs/fluent-bit/k8s-helm/http
    - name: Fluentd-Coralogix Chart
      if: steps.filter.outputs.logs-fluentd-http == 'true'
      run: scripts/version_bump_check.sh logs/fluentd/k8s-helm/coralogix
    - name: Fluentd-HTTP Chart
      if: steps.filter.outputs.logs-fluentd-http == 'true'
      run: scripts/version_bump_check.sh logs/fluentd/k8s-helm/http
    - name: OpenTelemetry Agent Chart
      if: steps.filter.outputs.otel-agent == 'true'
      run: scripts/version_bump_check.sh otel-agent/k8s-helm
    - name: OpenTelemetry Infrastructure Collector Chart
      if: steps.filter.outputs.otel-infrastructure-collector == 'true'
      run: scripts/version_bump_check.sh otel-infrastructure-collector/k8s-helm
    - name: OpenTelemetry Integration Chart
      if: steps.filter.outputs.otel-integration == 'true'
      run: scripts/version_bump_check.sh otel-integration/k8s-helm
    - name: Prometheus Agent Chart
      if: steps.filter.outputs.metrics-prometheus-agent == 'true'
      run: scripts/version_bump_check.sh metrics/prometheus-agent
    - name: Prometheus Operator Chart
      if: steps.filter.outputs.metrics-prometheus-operator == 'true'
      run: scripts/version_bump_check.sh metrics/prometheus/operator
