name: OpenTelemetry-Supervised-eBPF-Profiler Release
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      push_image:
        description: "Push image to registry"
        required: false
        default: false
        type: boolean
      image_name:
        description: "Image name (no organization or tag should be provided)"
        required: false
        default: "coralogix-otel-supervised-ebpf-profiler"
        type: string
      registry_org:
        description: "Container registry and organization"
        required: false
        default: "cgx.jfrog.io/coralogix-docker-images"
        type: choice
        options:
          - cgx.jfrog.io/coralogix-docker-images
          - docker.io/coralogixrepo
env:
  IMAGE_NAME: ${{ github.event.inputs.image_name || 'coralogix-otel-supervised-ebpf-profiler' }}
  REGISTRY_ORG: ${{ github.event.inputs.registry_org || 'docker.io/coralogixrepo' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        if: github.event.inputs.push_image == 'true' && github.event.inputs.registry_org == 'docker.io/coralogixrepo'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to CGX JFrog
        if: github.event.inputs.push_image == 'true' && github.event.inputs.registry_org == 'cgx.jfrog.io/coralogix-docker-images'
        uses: docker/login-action@v3
        with:
          registry: cgx.jfrog.io
          username: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image versions
        id: set-image-versions
        run: |
          image_version=$(cat ./otel-supervised-ebpf-profiler/CURRENT_IMAGE_VERSION | tr -d '[:space:]')
          collector_version=$(cat ./otel-supervised-ebpf-profiler/CURRENT_COLLECTOR_VERSION | tr -d '[:space:]')
          supervisor_version=$(cat ./otel-supervised-ebpf-profiler/CURRENT_SUPERVISOR_VERSION | tr -d '[:space:]')
          echo "image_version=${image_version}" >> "$GITHUB_OUTPUT"
          echo "collector_version=${collector_version}" >> "$GITHUB_OUTPUT"
          echo "supervisor_version=${supervisor_version}" >> "$GITHUB_OUTPUT"
          echo "Detected image version: ${image_version}"
          echo "Detected collector version: ${collector_version}"
          echo "Detected supervisor version: ${supervisor_version}"

      - name: Build and Push Supervised eBPF Profiler Image
        uses: docker/build-push-action@v5
        with:
          context: ./otel-supervised-ebpf-profiler/
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event.inputs.push_image == 'true' }}
          build-args: |
            COLLECTOR_VERSION=${{ steps.set-image-versions.outputs.collector_version }}
            SUPERVISOR_VERSION=${{ steps.set-image-versions.outputs.supervisor_version }}
          tags: |
            ${{ env.REGISTRY_ORG }}/${{ env.IMAGE_NAME }}:${{ steps.set-image-versions.outputs.image_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
